apiVersion: kubeadm.k8s.io/v1beta3
kind: InitConfiguration
localAPIEndpoint:
  advertiseAddress: A.B.C.D                                  # advertiseAddress: 172.17.1.74
  bindPort: 6443
---
apiServer:
  extraArgs:
    audit-log-path: /k8s-logs/apiserver/audit.log
    audit-policy-file: /k8s-policy/policy.yaml
  extraVolumes:
  - name: policy-conf
    hostPath: /etc/kubernetes/audit-policies/
    mountPath: /k8s-policy/
    pathType: DirectoryOrCreate
  - name: apiserver-log
    hostPath: /var/log/kubernetes/apiserver/
    mountPath: /k8s-logs/apiserver/
    pathType: DirectoryOrCreate
  timeoutForControlPlane: 4m0s
clusterName: K8S_CLUSTER_NAME                                # clusterName: k8s-alex
kind: ClusterConfiguration
kubernetesVersion: K8S_VERSION                               # kubernetesVersion: v1.28.15
networking:
  dnsDomain: cluster.local
  podSubnet: 10.244.0.0/16
  serviceSubnet: 10.96.0.0/12
scheduler: {}
