apiVersion: vmoperator.vmware.com/v1alpha3
kind: VirtualMachineService
metadata:
  namespace: demo-namespace-vkrcg
  name: lb-vm-redis
spec:
  selector:
    lb-vm-redis: vm-lb-selector
  type: LoadBalancer
  ports:
    - name: redis
      protocol: TCP
      port: 6379
      targetPort: 6379
    - name: ssh
      protocol: TCP
      port: 22
      targetPort: 22