apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: demo-namespace-vkrcg
  name: vote-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vote-frontend
  template:
    metadata:
      labels:
        app: vote-frontend
    spec:
      containers:
        - name: vote-frontend
          image: alexfr75/vote-app-frontend:v1.0
          ports:
            - containerPort: 80
          env:
            - name: REDIS
              value: lb-vm-redis