apiVersion: vmoperator.vmware.com/v1alpha5
kind: VirtualMachine
metadata:
  namespace: xbig-39r5b
  name: vm-redis
  labels:
    vm-selector: vm-redis
    lb-vm-redis: vm-lb-selector
spec:
  className: best-effort-small
  imageName: vmi-132dbd33bb2a92adb
  storageClass: vsan-default-storage-policy
  powerState: PoweredOn
  #powerState: PoweredOff
  network:
    domainName: labfr.com
    nameservers:
      - 8.8.8.8
  bootstrap:
    cloudInit:
      rawCloudConfig:
        name: vm-redis-bootstrap-secret2
        key: user-data
